version: '3'
services:
   redis:
      image: redis
      ports:
         - "6379:6379"
   mongo:
     image: mongo
     restart: always
     environment:
       MONGO_DB_ROOT_USERNAME: user
       MONGO_DB_ROOT_PASSWORD: pass
     ports:
       - "27017:27017"
   mongo-express:
     image: mongo-express
     restart: always
     ports:
       - "8081:8081"
     environment:
       ME_CONFIG_MONGODB_ADMINUSERNAME: root
       ME_CONFIG_MONGODB_ADMINPASSWORD: pass
       ME_CONFIG_MONGODB_URL: mongodb://user:pass@mongo:27017/
     depends_on:
       - mongo
   #  mysql:
   #    image: mariadb
   #    restart: always
   #    environment:
   #      MYSQL_ROOT_PASSWORD: pass
   #    ports:
   #      - "3306:3306"
#   kafka:
#      command:
#         - redpanda
#         - start
#         - --smp
#         - '1'
#         - --reserve-memory
#         - 0M
#         - --overprovisioned
#         - --node-id
#         - '0'
#         - --kafka-addr
#         - PLAINTEXT://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092
#         - --advertise-kafka-addr
#         - PLAINTEXT://redpanda:29092,OUTSIDE://localhost:9092
#      # NOTE: Please use the latest version here!
#      image: docker.vectorized.io/vectorized/redpanda:latest
#      ports:
#         - "9092:9092"
#         - "29092:29092"